name: Build Go Binaries

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            arch: amd64
            goos: linux
            goarch: amd64
          - os: ubuntu-latest
            platform: linux
            arch: arm64
            goos: linux
            goarch: arm64
          - os: windows-latest
            platform: windows
            arch: amd64
            goos: windows
            goarch: amd64
          - os: windows-latest
            platform: windows
            arch: arm64
            goos: windows
            goarch: arm64
          - os: macos-latest
            platform: darwin
            arch: amd64
            goos: darwin
            goarch: amd64
          - os: macos-latest
            platform: darwin
            arch: arm64
            goos: darwin
            goarch: arm64

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      # --- Build and Package for Linux/macOS ---
      - name: Build and Package (Linux/macOS)
        if: ${{ matrix.os != 'windows-latest' }} # Only run for non-Windows OSes
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          # Create the release directory
          mkdir -p release

          # Determine output binary name
          BINARY_NAME="cvgo-${{ matrix.platform }}-${{ matrix.arch }}"

          # Build the Go binary
          go build -o release/${BINARY_NAME} main.go

          # Copy additional files
          cp template.html release/
          cp data.json release/

          # Create the zip archive
          ZIP_NAME="cvgo-${{ matrix.platform }}-${{ matrix.arch }}.zip"
          cd release
          zip -r ../${ZIP_NAME} ./*
          cd .. # Go back to the root of the repository

      # --- Build and Package for Windows ---
      - name: Build and Package (Windows)
        if: ${{ matrix.os == 'windows-latest' }} # Only run for Windows OS
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          # Create the release directory
          mkdir -p release

          # Determine output binary name with .exe for Windows
          $BINARY_NAME = "cvgo-${{ matrix.platform }}-${{ matrix.arch }}.exe"

          # Build the Go binary
          go build -o release/$BINARY_NAME main.go

          # Copy additional files
          Copy-Item template.html release/
          Copy-Item data.json release/

          # Create the zip archive
          $ZIP_NAME = "cvgo-${{ matrix.platform }}-${{ matrix.arch }}.zip"
          Set-Location release
          Compress-Archive -Path * -DestinationPath ../$ZIP_NAME
          Set-Location .. # Go back to the root of the repository
        shell: pwsh # Explicitly use PowerShell for this step

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binary-${{ matrix.platform }}-${{ matrix.arch }}
          path: cvgo-${{ matrix.platform }}-${{ matrix.arch }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/binary-*/cvgo-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
